import {begin,finish,requireValue,ownKeys,approval,digest} from './guard.mjs';
export const actions=["identity.search","identity.read","identity.create","identity.update","identity.alias.link","identity.alias.unlink","identity.external-ref.link","identity.external-ref.unlink","identity.merge","identity.correct"];
const writes=actions.filter(a=>!["identity.search","identity.read"].includes(a));
export const initial=organization=>({organization,revision:0,operations:{},history:[],identities:{}});
export function execute(state,q){q=structuredClone(q);const c=begin(state,q,actions,writes);if(['identity.create','identity.update','identity.correct'].includes(q.action))requireValue(Object.keys(q.payload??{}).every(k=>q.authority.fields?.includes(k)&&q.authority.source_fields?.includes(k)),'FIELD_SOURCE_AUTHORITY');if(['identity.merge','identity.correct'].includes(q.action)){requireValue(q.authority.department==='Data'&&q.authority.relationship_conflicts_checked===true,'DATA_GOVERNANCE_REQUIRED');approval(q);}  if(c.replay)return {state:c.next,result:c.replay};
 const records=c.next.identities??={};
 const project=record=>Object.fromEntries(Object.entries(record).filter(([k])=>['id','kind','merged_into'].includes(k)||q.authority.fields?.includes(k)));
 if(q.action==='identity.search')return finish(c,q,Object.values(records).filter(r=>!r.merged_into&&q.authority.resources.includes(r.id)&&Object.values(project(r)).some(v=>String(v).toLowerCase().includes(String(q.payload?.query??'').toLowerCase()))).map(project));
 let r=records[q.target];
 if(q.action==='identity.read'){requireValue(r,'IDENTITY_NOT_FOUND');return finish(c,q,project(r))}
 if(q.action==='identity.create'){requireValue(!r,'IDENTITY_EXISTS');ownKeys(q.payload,['kind','display_name','contact_identifiers']);requireValue(['Person','Organization'].includes(q.payload.kind),'IDENTITY_KIND');r=records[q.target]={id:q.target,aliases:[],external_refs:[],...q.payload};}
 else {requireValue(r&&!r.merged_into,'IDENTITY_NOT_ACTIVE');
 if(['identity.update','identity.correct'].includes(q.action)){ownKeys(q.payload,['display_name','contact_identifiers']);if(q.action==='identity.correct'){requireValue(q.authority.department==='Data'&&q.authority.relationship_conflicts_checked===true,'DATA_GOVERNANCE_REQUIRED');approval(q)}Object.assign(r,q.payload)}
 else if(q.action.startsWith('identity.alias.')){ownKeys(q.payload,['alias']);requireValue(typeof q.payload.alias==='string'&&q.payload.alias,'ALIAS_REQUIRED');if(q.action.endsWith('link')&&!q.action.endsWith('unlink')){requireValue(!Object.values(records).some(x=>x.id!==r.id&&x.aliases.includes(q.payload.alias)),'ALIAS_CONFLICT');r.aliases=[...new Set([...r.aliases,q.payload.alias])]}else r.aliases=r.aliases.filter(a=>a!==q.payload.alias)}
 else if(q.action.startsWith('identity.external-ref.')){ownKeys(q.payload,['source','id']);requireValue(q.payload.source&&q.payload.id,'EXTERNAL_REF_REQUIRED');const key=digest(q.payload);if(q.action.endsWith('unlink'))r.external_refs=r.external_refs.filter(x=>digest(x)!==key);else {requireValue(!Object.values(records).some(x=>x.id!==r.id&&x.external_refs.some(v=>digest(v)===key)),'EXTERNAL_REF_CONFLICT');if(!r.external_refs.some(x=>digest(x)===key))r.external_refs.push(q.payload)}}
 else if(q.action==='identity.merge'){ownKeys(q.payload,['source_id']);requireValue(q.authority.department==='Data'&&q.authority.relationship_conflicts_checked===true,'DATA_GOVERNANCE_REQUIRED');approval(q);const from=records[q.payload.source_id];requireValue(from&&from.id!==r.id&&!from.merged_into&&from.kind===r.kind&&q.authority.resources.includes(from.id),'MERGE_SCOPE');requireValue(q.authority.fields?.includes('display_name'),'FIELD_SCOPE');r.aliases=[...new Set([...r.aliases,from.id,...from.aliases])];r.external_refs=[...r.external_refs,...from.external_refs.filter(x=>!r.external_refs.some(y=>digest(x)===digest(y)))];from.merged_into=r.id;}
 }
 if(['identity.create','identity.update','identity.correct'].includes(q.action)){requireValue(Object.keys(q.payload).every(k=>q.authority.fields?.includes(k)&&q.authority.source_fields?.includes(k)),'FIELD_SOURCE_AUTHORITY')}
 return finish(c,q,project(r));
}
